apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-server-clone
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis-server-clone
  template:
    metadata:
      labels:
        app: redis-server-clone
    spec:
      containers:
        - name: redis-clone
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
